name: Changelog

author: liblaf

description: TODO

inputs:
  args:
    description: Arguments to pass to git-cliff.
    required: false
    default: --verbose
  config:
    description: Path of the configuration file.
    required: false
  output:
    description: Output file.
    required: false
    default: ${{ runner.temp }}/CHANGELOG.md
  repository:
    description: The owner and repository name. For example, `octocat/Hello-World`.
    required: false
    default: ${{ github.repository }}
  token:
    description: GitHub API token.
    required: false
    default: ${{ github.token }}

outputs:
  changelog:
    description: Output file that contains the generated changelog.
    value: ${{ steps.cliff.outputs.changelog }}
  content:
    description: Content of the changelog.
    value: ${{ steps.output.outputs.content }}
  version:
    description: Version of the latest release.
    value: ${{ steps.cliff.outputs.version }}

runs:
  using: composite
  steps:
    - id: config
      name: Find Config
      run: |-
        if [[ -f "${{ inputs.config }}" ]]; then
          echo "config=${{ inputs.config }}" >> "$GITHUB_OUTPUT"
        else
          echo "config=$GITHUB_ACTION_PATH/cliff.toml" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - id: cliff
      name: git-cliff
      uses: orhun/git-cliff-action@v4
      with:
        args: ${{ inputs.args }}
        config: ${{ inputs.config || steps.config.outputs.config }}
      env:
        GITHUB_REPO: ${{ inputs.repository }}
        GITHUB_TOKEN: ${{ inputs.token }}
        OUTPUT: ${{ inputs.output }}
    - run: npx prettier --write "${{ inputs.output }}"
      shell: bash
      name: Prettier
    - run: |-
        echo "content<<EOF" >> "$GITHUB_OUTPUT"
        cat "${{ inputs.output }}" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
      shell: bash
      name: Set Output
      id: output
