# https://github.com/oxsecurity/megalinter/blob/main/mega-linter-runner/generators/mega-linter/templates/mega-linter.yml
# https://megalinter.io

name: MegaLinter

author: liblaf

description: TODO

inputs:
  github-status-reporter:
    description: TODO
    required: false
    default: "false"
  sarif-reporter:
    description: TODO
    required: false
    default: "false"
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Prepare Linter Config
      run: bash "${{ github.action_path }}/scripts/prepare.sh"
      shell: bash
    - name: MegaLinter
      uses: oxsecurity/megalinter@v8
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        # https://megalinter.io/latest/config-variables/
        # Common Variables
        VALIDATE_ALL_CODEBASE: true
        # Reporters
        TEXT_REPORTER: true
        GITHUB_COMMENT_REPORTER: true
        GITHUB_STATUS_REPORTER: ${{ inputs.github-status-reporter }}
        SARIF_REPORTER: ${{ inputs.sarif-reporter }}
        UPDATED_SOURCES_REPORTER: true
        CONFIG_REPORTER: true
        CONSOLE_REPORTER: true
        JSON_REPORTER: true
        MARKDOWN_SUMMARY_REPORTER: true
    - if: always()
      name: Remove Linter Config
      run: bash "${{ github.action_path }}/scripts/remove.sh"
      shell: bash
    - if: always()
      name: Archive Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: megalinter-reports
        path: |-
          mega-linter.log
          megalinter-reports/
    - if: always() && inputs.sarif-reporter == 'true'
      name: Upload Megalinter Scan Results To Github Security Tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: megalinter-reports/megalinter-report.sarif
      continue-on-error: true
    - if: always()
      name: Add GitHub Summary
      run: cat "megalinter-reports/megalinter-report.md" >> "$GITHUB_STEP_SUMMARY"
      shell: bash
      continue-on-error: true
    - if: always()
      name: Prepare Commit
      run: sudo chown --changes --recursive $UID .git/
      shell: bash
