# https://github.com/oxsecurity/megalinter/blob/main/mega-linter-runner/generators/mega-linter/templates/mega-linter.yml
# https://megalinter.io

name: MegaLinter

author: liblaf

description: TODO

inputs:
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Prepare Linter Rules
      run: bash "${{ github.action_path }}/scripts/prepare.sh"
      shell: bash
    - id: config
      name: Discover Configuration
      run: |-
        MEGALINTER_CONFIG_OPTIONS=(
          .mega-linter.yaml
          .mega-linter.yml
          .github/.mega-linter.yaml
          .github/.mega-linter.yml
          "${{ github.action_path }}/.mega-linter.yaml"
        )

        for config in "${MEGALINTER_CONFIG_OPTIONS[@]}"; do
          if [[ -f $config ]]; then
            echo "MEGALINTER_CONFIG=$config" >> "$GITHUB_ENV"
          fi
        done
      shell: bash
    - name: MegaLinter
      uses: oxsecurity/megalinter@v8
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        # https://megalinter.io/latest/config-variables/
        # Common Variables
        VALIDATE_ALL_CODEBASE: true
        # Reporters
        TEXT_REPORTER: true
        GITHUB_COMMENT_REPORTER: true
        GITHUB_STATUS_REPORTER: true
        SARIF_REPORTER: true
        UPDATED_SOURCES_REPORTER: true
        CONFIG_REPORTER: true
        CONSOLE_REPORTER: true
        JSON_REPORTER: true
        MARKDOWN_SUMMARY_REPORTER: true
    - if: success() || failure()
      name: Remove Linter Rules
      run: bash "${{ github.action_path }}/scripts/remove.sh"
      shell: bash
    - if: success() || failure()
      name: Archive Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: megalinter-reports
        path: |-
          mega-linter.log
          megalinter-reports/
    - if: success() || failure()
      name: Upload Megalinter Scan Results To Github Security Tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: megalinter-reports/megalinter-report.sarif
      continue-on-error: true
    - if: success() || failure()
      name: Add GitHub Summary
      run: cat "megalinter-reports/megalinter-report.md" >> "$GITHUB_STEP_SUMMARY"
      shell: bash
      continue-on-error: true
    - if: success() || failure()
      name: Prepare Commit
      run: sudo chown --changes --recursive $UID .git/
      shell: bash
      continue-on-error: true
