name: Approve

author: liblaf

description: Approve

inputs:
  authors:
    description: authors
    required: false
    default: |-
      app/renovate
  filters:
    description: filters
    required: false
    default: >-
      --app renovate
      --state open
  pr-number:
    description: PR number
    required: false
    default: ${{ github.event.pull_request.number || github.event.pull_request_review.pull_request.number }}
  repo:
    description: Repository name with owner
    required: false
    default: ${{ github.repository }}
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Review
      run: bash '${{ github.action_path }}/main.sh'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        INPUT_AUTHORS: ${{ inputs.authors }}
        INPUT_FILTERS: ${{ inputs.filters }}
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
        INPUT_REPO: ${{ inputs.repo }}
