# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
# ref: <https://github.com/MercuryTechnologies/delete-cancelled-runs>

name: Delete Cancelled Runs

description: Deletes cancelled runs for a given workflow

inputs:
  max-deletions:
    description: The maximum number of cancelled runs to delete
    required: false
    default: "3"
  token:
    description: GitHub access token
    required: false
    default: ${{ github.token }}
  workflow:
    description: The basename of the workflow file
    required: false
    default: ${{ github.workflow_ref }}

runs:
  using: composite
  steps:
    - id: inputs
      name: Parse Inputs
      run: |-
        workflow='${{ inputs.workflow }}'
        workflow="${workflow%'@'*}"
        workflow="${workflow##*'/'}"
        printf 'workflow=%s\n' "$workflow" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Delete Cancelled Runs
      uses: MercuryTechnologies/delete-cancelled-runs@1.0.0
      with:
        workflow-file: ${{ steps.inputs.outputs.workflow }}
        max-deletions: ${{ inputs.max-deletions }}
        github-token: ${{ inputs.token }}
