name: Setup Python

author: liblaf

description: TODO

inputs:
  python-version:
    description: The version of Python to set UV_PYTHON to
    required: false

runs:
  using: composite
  steps:
    - if: hashFiles('**/pixi.lock') != ''
      name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0
      with:
        run-install: true
        activate-environment: true
        locked: false
    - if: hashFiles('**/uv.lock') != ''
      name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
