name: Release

author: liblaf

description: The `release` action automates the process of creating a release on GitHub, including generating a changelog, formatting it, and uploading specified assets.

inputs:
  clobber:
    description: Recreate the release if it already exists
    required: false
    default: "false"
  files:
    description: Newline-delimited list of path globs for asset files to upload
    required: false
  hasher:
    description: Compute hashsums using the specified digest algorithm
    required: false
    default: sha256
  prerelease:
    description: Mark the release as a prerelease
    required: false
    default: "false"
  repo:
    description: Repository name with owner
    required: false
    default: ${{ github.repository }}
  tag:
    description: Tag name
    required: true
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        path: _tmp.W8nAhH91eW
        fetch-depth: 0
    - name: Generate Changelog
      id: changelog
      env:
        OUTPUT: ${{ runner.temp }}/CHANGELOG.md
        GIT_CLIFF_REPOSITORY: _tmp.W8nAhH91eW
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPO: ${{ inputs.repo }}
      uses: orhun/git-cliff-action@v4
      with:
        config: ${{ github.action_path }}/cliff.toml
        args: --unreleased --strip all
        github_token: ${{ inputs.token }}
    - run: npx prettier --write --ignore-path "" "${{ steps.changelog.outputs.changelog }}"
      shell: bash
      name: Format Changelog
    - run: pipx run --spec git+https://github.com/liblaf/actions.git --python 3.12 --fetch-missing-python release
      shell: bash
      name: Release
      env:
        FORCE_COLOR: 1
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_CHANGELOG_FILE: ${{ steps.changelog.outputs.changelog }}
        INPUT_CLOBBER: ${{ inputs.clobber }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_HASHER: ${{ inputs.hasher }}
        INPUT_PRERELEASE: ${{ inputs.prerelease }}
        INPUT_REPO: ${{ github.repository }}
        INPUT_TAG: ${{ inputs.tag }}
    - run: rm -fr _tmp.W8nAhH91eW
      shell: bash
      name: Cleanup
