name: Release

author: liblaf

description: The `release` action automates the process of creating a release on GitHub, including generating a changelog, formatting it, and uploading specified assets.

inputs:
  clobber:
    description: Recreate the release if it already exists
    required: false
    default: "false"
  files:
    description: Newline-delimited list of path globs for asset files to upload
    required: false
  hasher:
    description: Compute hashsums using the specified digest algorithm
    required: false
    default: sha256
  prerelease:
    description: Mark the release as a prerelease
    required: false
    default: "false"
  repo:
    description: Repository name with owner
    required: false
    default: ${{ github.repository }}
  tag:
    description: Tag name
    required: true
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - id: config
      name: Config
      run: |-
        if [[ ${{ inputs.prerelease }} == "true" ]]; then
          echo "args=--unreleased --tag ${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
        else
          echo "args=--current" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - id: changelog
      name: Generate Changelog
      uses: liblaf/actions/changelog@main
      with:
        args: ${{ steps.config.outputs.args }} --strip all
        token: ${{ inputs.token }}
    - name: Release
      run: pipx run --spec "git+https://github.com/liblaf/actions.git" --fetch-missing-python release
      shell: bash
      env:
        FORCE_COLOR: "1"
        INPUT_CHANGELOG_FILE: ${{ steps.changelog.outputs.changelog }}
        INPUT_CLOBBER: ${{ inputs.clobber }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_HASHER: ${{ inputs.hasher }}
        INPUT_PRERELEASE: ${{ inputs.prerelease }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_TOKEN: ${{ inputs.token }}
