name: Setup GitHub Pages

author: liblaf

description: TODO

inputs:
  repo:
    description: repo
    required: false
    default: ${{ github.repository }}
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: false
    - name: Setup GitHub Pages
      run: uv run "$GITHUB_ACTION_PATH/main.py"
      shell: bash
      env:
        FORCE_COLOR: "1"
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_TOKEN: ${{ inputs.token }}
