name: (Bot) Copier Update

run-name: Copier Update (${{ inputs.owner }}/${{ inputs.repo }})

on:
  workflow_dispatch:
    inputs:
      owner:
        required: true
        type: string
        description: The account owner of the repository. The name is not case sensitive.
      repo:
        required: true
        type: string
        description: The name of the repository without the .git extension. The name is not case sensitive.

jobs:
  copier-update:
    runs-on: ubuntu-latest
    steps:
      - id: auth-app
        name: Authenticate with GitHub App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repo }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ steps.auth-app.outputs.token }}
      - name: Copier Update
        uses: liblaf/actions/copier-update@main
        with:
          repo: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ steps.auth-app.outputs.token }}
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(copier): update from template"
          commit_user_name: ${{ steps.auth-app.outputs.commit-user-name }}
          commit_user_email: ${{ steps.auth-app.outputs.commit-user-email }}
          commit_author: ${{ steps.auth-app.outputs.commit-author }}
