name: (Bot) Schedule

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Schedule
        run: pipx run --spec . --python 3.12 --fetch-missing-python schedule
        env:
          INPUT_APP_ID: ${{ vars.APP_ID }}
          INPUT_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
