name: Sync with Repository Template

on:
  workflow_dispatch:
    inputs:
      owner:
        required: true
        type: string
        description: The account owner of the repository. The name is not case sensitive.
      repo:
        required: true
        type: string
        description: The name of the repository without the .git extension. The name is not case sensitive.

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - id: auth-app
        name: Authenticate with GitHub App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Sync with Repository Template
        run: |-
          gh workflow --repo liblaf/repo run sync.yaml \
            --field owner="${{ inputs.owner }}" \
            --field repo="${{ inputs.repo }}"
        env:
          GH_TOKEN: ${{ steps.auth-app.outputs.token }}
