name: Set Secret

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Secret Set
        run: ./scripts/secret-set.sh
        env:
          GH_TOKEN: ${{ secrets.PAT || github.token }}
          OWNER: ${{ github.repository_owner }}
          PAT: ${{ secrets.PAT }}
