name: Test app-list-repos

on:
  push:

jobs:
  list-repos:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.list-repos.outputs.repos }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: list-repos
        name: App List Repos
        uses: ./app-list-repos
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: List Repositories
        run: echo "${{ steps.list-repos.outputs.repos }}"
        shell: bash

  echo:
    name: Echo
    runs-on: ubuntu-latest
    needs:
      - list-repos
    steps:
      - name: Echo Repos
        run: |-
          echo "repo: ${{ matrix.owner }}/${{ matrix.repo }}"
        shell: bash
    strategy:
      matrix:
        include: ${{ fromJson(needs.list-repos.outputs.repos) }}
